# The URL the site will be built for
base_url = "https://pittnail.github.io/EBAIC"
description = "The First International Workshop on Ethics and Bias of Artificial Intelligence in Clinical Applications (EBAIC 2023)"
title = "EBAIC 2023"

compile_sass = true
build_search_index = false
theme = "zolastrap"
sort_by = "none"

[markdown]
highlight_code = true

[extra]
themes = ""
schemes = ""
banner = "banner.png"
